ebarbeito_job:
    pattern:  /
    defaults: { _controller: "ebarbeitoJobeetBundle:Job:index" }

ebarbeito_job_show:
    pattern:  /{company}/{location}/{id}/{position}
    defaults: { _controller: "ebarbeitoJobeetBundle:Job:show" }
    requirements:
        id:  \d+

ebarbeito_job_new:
    pattern:  /new
    defaults: { _controller: "ebarbeitoJobeetBundle:Job:new" }

ebarbeito_job_create:
    pattern:  /create
    defaults: { _controller: "ebarbeitoJobeetBundle:Job:create" }
    requirements: { _method: post }

ebarbeito_job_edit:
    pattern:  /{id}/edit
    defaults: { _controller: "ebarbeitoJobeetBundle:Job:edit" }

ebarbeito_job_update:
    pattern:  /{id}/update
    defaults: { _controller: "ebarbeitoJobeetBundle:Job:update" }
    requirements: { _method: post|put }

ebarbeito_job_delete:
    pattern:  /{id}/delete
    defaults: { _controller: "ebarbeitoJobeetBundle:Job:delete" }
    requirements: { _method: post|delete }
