ebarbeitoJobeetBundle_job:
    resource: "@ebarbeitoJobeetBundle/Resources/config/routing/job.yml"
    prefix:   /job

ebarbeitoJobeetBundle_category:
    pattern: /category/{slug}/{page}
    defaults: { _controller: ebarbeitoJobeetBundle:Category:show, page: 1 }

ebarbeitoJobeetBundle_hello:
    pattern:  /hello/{name}
    defaults: { _controller: ebarbeitoJobeetBundle:Default:index }
        
ebarbeito_jobeet_homepage:
    pattern:  /
    defaults: { _controller: ebarbeitoJobeetBundle:Job:index }
