ebarbeitoJobeetBundle_job:
    resource: "@ebarbeitoJobeetBundle/Resources/config/routing/job.yml"
    prefix:   /job
        
ebarbeito_jobeet_homepage:
    pattern:  /
    defaults: { _controller: ebarbeitoJobeetBundle:Job:index }
